# Generated by Django 5.0.1 on 2024-01-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='qr_code_imd',
            new_name='qr_code_img',
        ),
    ]
