# Generated by Django 5.0.1 on 2024-01-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_qr_code_imd_item_qr_code_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='items',
            field=models.ManyToManyField(to='api.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qr_code_img',
            field=models.FileField(blank=True, null=True, upload_to='qr_code_img/'),
        ),
    ]
