# Generated by Django 5.0.1 on 2024-01-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subject_items_alter_item_qr_code_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='items',
            field=models.ManyToManyField(blank=True, to='api.item'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, to='api.student'),
        ),
    ]
